### PR TITLE
Fixed Security issue

### PR DESCRIPTION
**Pull request by wr3nch0x1**
Fixed Insecure randomness vulnerability

### CODE REVIEW

**Comment by overtrue** [comment]
Thanks

**Comment by wr3nch0x1** [comment]
Hi admins,

Can you please approve my vulnerability on huntr.dev please?

It will help me get bounty amount from the owner of hunder.dev and badges.

Thank you.

**Comment by overtrue** [comment]
@wr3nch0x1 how to approve? show me the link?

**Comment by wr3nch0x1** [comment]
Here you go: https://www.huntr.dev/bounties/1624909120370-w7corp/easywechat/

Please accept both fix and disclosure. :)

In case, if I have found a few more bugs, I will share the pull on the same
page in future.

**Comment by overtrue** [comment]
@wr3nch0x1 Sorry, It seems something wrong: 

image

**Comment by JamieSlome** [comment]
@overtrue - it should work now, you should be able to see the report!

**Comment by overtrue** [comment]
OK, I see it.

**Comment by JamieSlome** [comment]
@overtrue - if you could mark it as valid and confirm that @wr3nch0x1 provided the fix by using the `mark as valid` and `confirm fix` buttons.

**Comment by overtrue** [comment]
@JamieSlome OK, done.

**Comment by JamieSlome** [comment]
@overtrue - thank you 🙏 

If you are interested in receiving more security disclosures, you can stick our badge on your `README.md`:

`[huntr](https://huntr.dev)`

[huntr](https://huntr.dev)

**Comment by overtrue** [comment]
Thanks, I have added it.

**Comment by JamieSlome** [comment]
Great! 🎉

**Pull request merged**
